### PR TITLE
Update to JupyterLab 4

### LINKED ISSUE #31: Missing file browser toolbar items with JupyterLab 3.4.0
## Description

The file browser toolbar is missing a couple of items with JupyterLab 3.4.0.

**With JupyterLab 3.3.4**

image

**With JupyterLab 3.4.0**

image

## Reproduce

- `pip install jupyterlab>=3.4.0 jupyterlab-filesystem-access`
- Open JupyterLab

## Context

This is most likely related to https://github.com/jupyterlab/jupyterlab/pull/12281

- Python package version: 0.4.0

- Extension version: 0.4.0

- Operating System and its version:  Ubuntu 20.04 - Chromium 101

### LINKED ISSUE #54: Extension does not work in JupyterLab v4
The extension does not seem to work in JupyterLab v4:

- the extension icon does not render in the side toolbar, and as such, the extension functionality appears not to be accessible.

### LINKED ISSUE #57: Add the Jupyter Releaser release workflows
Currently releases are done via the Jupyter releaser fork.

We should add the workflows to make releases from the repo.

And set up the repo to use the `jupyterlab-contrib` credentials.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #31 
Fixes #54 
Fixes #57 
Closes https://github.com/jupyterlab-contrib/jupyterlab-filesystem-access/pull/32

[lite-badge](https://jupyterlab-filesystem-access--55.org.readthedocs.build/en/55/lite/lab/index.html)

- [x] Bootstrap the update with the update script: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#upgrading-extension-using-the-upgrade-script
- [x] Enable toolbar items

image

image

### CODE REVIEW

**Comment by jtpio** [comment]
Looking good at first:

image


Some dev tools errors that might be related to the update:

image

**Comment by jtpio** [comment]
While the current JupyterLite version seems to be working fine accessing files from the kernel:

image


Using this branch with the latest `jupyterlite-*`packages gives the following error:

image

**Comment by jtpio** [comment]
Checking with `jupyterlite-pyodide-kernel==0.2.0a2`, `jupyterlite-core==0.2.0rc1` and the current version of `jupyterlab-filesystem-access` (`0.5.3`, the extension is built against JupyterLab 3 but activates fine in JupyterLab 4):

image

So this might be more of an issue with the latest `jupyterlite-*` packages when accessing drive content from the kernel, than an issue with this PR updating to JupyterLab 4.

**Comment by jtpio** [comment]
Hopefully this will be fixed in https://github.com/jupyterlite/jupyterlite/pull/1227.

**Comment by jtpio** [comment]
Getting this one in to follow-up with https://github.com/jupyterlab-contrib/jupyterlab-filesystem-access/issues/58.

**Comment by martinRenou** [comment]
Great thanks!

**Pull request merged**
