### PR TITLE
Emit fileChanged after rename

### LINKED ISSUE #40: Emit signal after renaming a file
Description in https://github.com/jupyterlab/jupyterlab/pull/12849#issuecomment-1200405717

### PR DESCRIPTION
**Pull request by hbcarlos**
fixes #40

### CODE REVIEW

**Review by martinRenou — APPROVED** [review]
Thank you!

**Comment by jtpio** [comment]
The windows failure looks odd since the PR doesn't modify css files.

Will have a look.

**Comment by jtpio** [comment]
Ci failure is also happening in https://github.com/jupyterlab-contrib/jupyterlab-filesystem-access/pull/42

**Comment by hbcarlos** [comment]
I rebased on main and squashed @jtpio's commit. The test should pass now.

**Comment by martinRenou** [comment]
Thanks!

**Pull request merged**
